EXE = ant
OBJS = main.o pmatrix.o cmatrix.o path.o
CLEAN_RM = 

# 0	- Default, optimization for compilation time
# 1	- Optimization for code size and execution time
# 2	- Optimization for code size and more for execution time
# 3	- Optimization for code size and even more for execution time
# s	- Optimization more for code size
# fast - O3 with fast none accurate math calculations
OPT_LVL = fast

include ../_make/generic.mk